services:
  postgres:
    image: postgres:16-alpine
    container_name: romulus-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-romulus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-romulus}
      POSTGRES_DB: ${POSTGRES_DB:-romulus}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U romulus"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: romulus-minio
    command: server /data --console-address ":9001"
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - ./.assets:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_SERVER_URL=http://localhost:9000
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: romulus-api
    network_mode: "host"
    entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-8000} --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://romulus:romulus@localhost:${POSTGRES_PORT:-5432}/romulus
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD:-minioadmin}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
          ignore:
            - __pycache__/
            - .venv/
            - .pytest_cache/
            - "*.pyc"
        - action: rebuild
          path: ./backend/pyproject.toml

volumes:
  postgres_data: