services:
  postgres:
    image: postgres:16-alpine
    container_name: romulus-postgres
    environment:
      POSTGRES_USER: romulus
      POSTGRES_PASSWORD: romulus
      POSTGRES_DB: romulus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U romulus"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: romulus-api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://romulus:romulus@postgres:5432/romulus
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - __pycache__/
            - .venv/
            - .pytest_cache/
            - "*.pyc"
        - action: rebuild
          path: ./pyproject.toml

volumes:
  postgres_data: