"""Add unique constraint for scene name per game

Revision ID: 0d4b1f942ad8
Revises: b06aa0715ee0
Create Date: 2025-10-26 00:04:19.445117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4b1f942ad8'
down_revision: Union[str, Sequence[str], None] = 'b06aa0715ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_scene_game_name', 'scenes', ['game_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_scene_game_name', 'scenes', type_='unique')
    # ### end Alembic commands ###
