"""Add Entity table

Revision ID: 49c9b1097ca6
Revises: 7ad237cf61be
Create Date: 2025-10-28 04:49:56.527407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.pydantic_type import PydanticType
from core.schemas import NESEntity


# revision identifiers, used by Alembic.
revision: str = '49c9b1097ca6'
down_revision: Union[str, Sequence[str], None] = '7ad237cf61be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_data', PydanticType(NESEntity), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scene_id', 'name', name='uq_entity_scene_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entities')
    # ### end Alembic commands ###
