"""Add resources table

Revision ID: 7ad237cf61be
Revises: c2eb527c5252
Create Date: 2025-10-28 04:35:39.884477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from core.pydantic_type import PydanticType
from core.schemas import ResourceData


# revision identifiers, used by Alembic.
revision: str = '7ad237cf61be'
down_revision: Union[str, Sequence[str], None] = 'c2eb527c5252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('type', sa.Enum('IMAGE', name='resourcetype'), nullable=False),
    sa.Column('resource_data', PydanticType(ResourceData), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
