"""Add processed flag to image assets

Revision ID: a2b44df14537
Revises: 17331b8d005f
Create Date: 2025-10-28 19:13:43.448366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2b44df14537'
down_revision: Union[str, Sequence[str], None] = '17331b8d005f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compiled_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compiled_assets',
    sa.Column('game_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('PALETTE', name='compiledassettype'), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_compiled_assets_game_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('compiled_assets_pkey')),
    sa.UniqueConstraint('game_id', 'name', 'type', name=op.f('uq_compiled_asset_game_name_type'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
