"""Add Component table

Revision ID: c2eb527c5252
Revises: 0d4b1f942ad8
Create Date: 2025-10-26 12:36:26.343444

"""
from typing import Sequence, Union

from alembic import op
from core.schemas import ComponentData
import sqlalchemy as sa
from core.pydantic_type import PydanticType


# revision identifiers, used by Alembic.
revision: str = 'c2eb527c5252'
down_revision: Union[str, Sequence[str], None] = '0d4b1f942ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('game_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('PALETTE', name='componenttype'), nullable=False),
    sa.Column('component_data', PydanticType(ComponentData), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', 'type', name='uq_component_game_name_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('components')
    # ### end Alembic commands ###
