"""Add entity_id to components table

Revision ID: df3dd17246c3
Revises: 5e33375f7d87
Create Date: 2025-11-01 20:59:11.686852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3dd17246c3'
down_revision: Union[str, Sequence[str], None] = '5e33375f7d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('entity_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'components', 'entities', ['entity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_column('components', 'entity_id')
    # ### end Alembic commands ###
