"""Use source_url for parent asset references instead of IDs

Revision ID: f6d0a8cccb2b
Revises: d9998f990d35
Create Date: 2025-10-28 17:18:01.981566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d0a8cccb2b'
down_revision: Union[str, Sequence[str], None] = 'd9998f990d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
